// Catálogo de produtos da X-mart.
// Isto é dado de exemplo — troque nome, preço, estoque e specs pelos produtos reais da loja.
// "icon" define o ícone/placeholder visual usado até termos fotos reais dos produtos.

const CATEGORIES = [
  { slug: 'celulares',  name: 'Celulares',   icon: 'phone' },
  { slug: 'acessorios', name: 'Acessórios',  icon: 'case' },
  { slug: 'audio',      name: 'Som & Fones', icon: 'headphone' },
  { slug: 'smartwatch', name: 'Smartwatch',  icon: 'watch' },
  { slug: 'tv',         name: "TV’s",        icon: 'tv' },
];

const PRODUCTS = [
  {
    id: 'iphone-17-pro-max',
    name: 'iPhone 17 Pro Max',
    category: 'celulares',
    icon: 'phone',
    price: 9499,
    oldPrice: 10299,
    stock: 6,
    tag: 'Lançamento',
    short: 'Tela Super Retina XDR, chip A19 Pro e sistema de câmeras Pro.',
    desc: 'O mais novo da linha Pro da Apple, com desempenho de ponta, gravação em ProRes e bateria para o dia inteiro. Produto lacrado, importado dos EUA, com garantia X-mart.',
    options: { Cor: ['Titânio Preto', 'Titânio Natural', 'Titânio Dourado'], Armazenamento: ['256GB', '512GB', '1TB'] },
    specs: { Tela: '6.9" Super Retina XDR', Processador: 'Apple A19 Pro', Câmera: 'Tripla 48MP', Bateria: 'Até 29h de vídeo', Garantia: '12 meses X-mart' },
  },
  {
    id: 'iphone-16',
    name: 'iPhone 16 128GB',
    category: 'celulares',
    icon: 'phone',
    price: 5799,
    oldPrice: null,
    stock: 10,
    tag: null,
    short: 'Chip A18, câmera dupla de 48MP e Siri mais inteligente.',
    desc: 'Equilíbrio perfeito entre desempenho e preço, com a qualidade Apple de sempre. Lacrado, nota fiscal e garantia.',
    options: { Cor: ['Preto', 'Azul', 'Rosa', 'Verde-acinzentado'], Armazenamento: ['128GB', '256GB'] },
    specs: { Tela: '6.1" Super Retina XDR', Processador: 'Apple A18', Câmera: 'Dupla 48MP', Bateria: 'Até 22h de vídeo', Garantia: '12 meses X-mart' },
  },
  {
    id: 'galaxy-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra',
    category: 'celulares',
    icon: 'phone',
    price: 7299,
    oldPrice: 7999,
    stock: 5,
    tag: 'Oferta',
    short: 'Câmera de 200MP, S Pen integrada e tela de 6.9".',
    desc: 'O topo de linha Samsung, com IA Galaxy, tela Dynamic AMOLED 2X e desempenho para jogos pesados e produtividade.',
    options: { Cor: ['Preto Titânio', 'Cinza Titânio'], Armazenamento: ['256GB', '512GB'] },
    specs: { Tela: '6.9" Dynamic AMOLED 2X', Processador: 'Snapdragon 8 Elite', Câmera: 'Quádrupla 200MP', Bateria: '5000mAh', Garantia: '12 meses X-mart' },
  },
  {
    id: 'redmi-note-14',
    name: 'Xiaomi Redmi Note 14',
    category: 'celulares',
    icon: 'phone',
    price: 1799,
    oldPrice: 1999,
    stock: 14,
    tag: 'Mais vendido',
    short: 'Custo-benefício com câmera de 108MP e carregamento rápido.',
    desc: 'A escolha certa para quem quer um aparelho rápido no dia a dia sem pesar no bolso.',
    options: { Cor: ['Preto', 'Verde', 'Lavanda'], Armazenamento: ['128GB', '256GB'] },
    specs: { Tela: '6.67" AMOLED 120Hz', Processador: 'Snapdragon 6s Gen 3', Câmera: '108MP', Bateria: '5500mAh', Garantia: '12 meses X-mart' },
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro 2',
    category: 'audio',
    icon: 'headphone',
    price: 1699,
    oldPrice: 1899,
    stock: 9,
    tag: null,
    short: 'Cancelamento de ruído ativo e áudio espacial.',
    desc: 'Som imersivo com case de recarga MagSafe. Ideal para quem já tem iPhone.',
    options: { Cor: ['Branco'] },
    specs: { Tipo: 'Intra-auricular', Bateria: 'Até 6h + 24h no case', Conexão: 'Bluetooth 5.3', Garantia: '12 meses X-mart' },
  },
  {
    id: 'caixa-jbl-charge-5',
    name: 'Caixa de Som JBL Charge 5',
    category: 'audio',
    icon: 'speaker',
    price: 999,
    oldPrice: null,
    stock: 7,
    tag: null,
    short: 'Som potente, à prova d\'água e com power bank integrado.',
    desc: 'Perfeita para festa, praia ou trabalho — resistência IP67 e até 20h de bateria.',
    options: { Cor: ['Preto', 'Azul', 'Vermelho'] },
    specs: { Potência: '40W RMS', Bateria: 'Até 20h', Resistência: 'IP67', Garantia: '12 meses X-mart' },
  },
  {
    id: 'watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    category: 'smartwatch',
    icon: 'watch',
    price: 6499,
    oldPrice: null,
    stock: 3,
    tag: 'Últimas unidades',
    short: 'Caixa de titânio, GPS de precisão e até 36h de bateria.',
    desc: 'O relógio mais resistente da Apple, pensado para esporte, mergulho e uso intenso no dia a dia.',
    options: { Pulseira: ['Alpine Loop', 'Trail Loop', 'Ocean Band'] },
    specs: { Caixa: '49mm Titânio', Bateria: 'Até 36h', Resistência: '100m', Garantia: '12 meses X-mart' },
  },
  {
    id: 'galaxy-watch-7',
    name: 'Samsung Galaxy Watch 7',
    category: 'smartwatch',
    icon: 'watch',
    price: 1699,
    oldPrice: 1899,
    stock: 8,
    tag: null,
    short: 'Monitoramento de saúde completo e tela sempre ativa.',
    desc: 'Acompanha sono, treino e frequência cardíaca com precisão, integrado ao Galaxy AI.',
    options: { Cor: ['Preto', 'Prata'] },
    specs: { Caixa: '44mm Alumínio', Bateria: 'Até 40h', Resistência: '5ATM + IP68', Garantia: '12 meses X-mart' },
  },
  {
    id: 'smart-tv-55-4k',
    name: 'Smart TV 55" 4K',
    category: 'tv',
    icon: 'tv',
    price: 2599,
    oldPrice: 2899,
    stock: 4,
    tag: 'Oferta',
    short: 'Resolução 4K, HDR e sistema com os principais apps de streaming.',
    desc: 'Imagem nítida e som envolvente para transformar a sala de casa em cinema.',
    options: { Tamanho: ['50"', '55"', '65"'] },
    specs: { Resolução: '4K UHD', HDR: 'HDR10+', Conexões: '3x HDMI, 2x USB', Garantia: '12 meses X-mart' },
  },
  {
    id: 'carregador-turbo-33w',
    name: 'Carregador Turbo 33W',
    category: 'acessorios',
    icon: 'charger',
    price: 89,
    oldPrice: 119,
    stock: 40,
    tag: null,
    short: 'Carregamento rápido compatível com iPhone e Android.',
    desc: 'Recarrega até 50% da bateria em 30 minutos nos aparelhos compatíveis.',
    options: { Tipo: ['USB-C', 'Duplo USB-C'] },
    specs: { Potência: '33W', Entrada: 'Bivolt', Compatibilidade: 'iPhone / Android', Garantia: '90 dias' },
  },
  {
    id: 'capinha-anti-impacto',
    name: 'Capinha Anti-Impacto',
    category: 'acessorios',
    icon: 'case',
    price: 49,
    oldPrice: null,
    stock: 60,
    tag: null,
    short: 'Proteção reforçada nas bordas e câmera.',
    desc: 'Disponível para diversos modelos de iPhone e Samsung — confira o modelo do seu aparelho.',
    options: { Modelo: ['iPhone 16', 'iPhone 15', 'Galaxy S25', 'Galaxy S24'] },
    specs: { Material: 'TPU + PC', Proteção: 'Bordas reforçadas', Garantia: '90 dias' },
  },
];

function getProduct(id){ return PRODUCTS.find(p => p.id === id); }
function getCategory(slug){ return CATEGORIES.find(c => c.slug === slug); }
function formatBRL(v){ return v.toLocaleString('pt-BR', { style:'currency', currency:'BRL' }); }
